Update code to Swift 3
twitterdev/cannonball-ios pull request #8
Opened 2017-01-31 20:54 UTC by alexsinger

2017-03-28 21:11 UTC, danasilver requested changes

2017-03-28 21:11 UTC, danasilver commented on Cannonball/SignInViewController.swift
>                  self.navigateToMainAppScreen()
Should wrap this in `DispatchQueue.main.async { }` to present on the main thread so next screen is shown.

```
DispatchQueue.main.async {
    // Navigate to the main app screen to select a theme.
    self.navigateToMainAppScreen()
}
```

2017-03-28 21:11 UTC, danasilver commented on Cannonball/ThemeChooserViewController.swift
>          if navigationController?.viewControllers.count > 1 {
Change to `if let vcCount = navigationController?.viewControllers.count, vcCount > 1 {` so we can remove the `FIXME` for comparison operators with optionals.

2017-03-28 21:11 UTC, danasilver commented on Cannonball/ThemeChooserViewController.swift
> +// FIXME: comparison operators with optionals were removed from the Swift Standard Libary.
Can remove both of these `FIXME`s after the change below.

2017-04-04 13:27 UTC, alexsinger commented
@danasilver I made your suggested changed. Let me know how it looks. Thanks!

2017-04-04 16:55 UTC, danasilver approved these changes

2017-04-04 16:55 UTC, danasilver commented
Looks great! Ship it! 💯

2017-04-06 16:54 UTC, merged